name: Windows CI

on: [pull_request]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install --no-optional
    - name: npm test
      run: npm run test:win
